clear;

Simulink.Bus.cellToObject(...
    {{ ...
    'FROM_LATTE_FLAG', ...
    '', ...
    '', ...
    [ ...
    {{'steer', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    {{'turn', 1, 'uint8', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'FROM_LATTE', ...
    '', ...
    '', ...
    [ ...
    {{'input_angle_r32', 1, 'single', -1 'real', 'Sample', 'Fixed'}} ...
    {{'input_velo_r32', 1, 'single', -1 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'MOTOR_CONTROL', ...
    '', ...
    '', ...
    [ ...
    {{'encoder_u16', 1, 'uint16', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'motor_dir_u16', 1, 'uint16', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})

Simulink.Bus.cellToObject(...
    {{ ...
    'RETURN', ...
    '', ...
    '', ...
    [ ...
    {{'motor_dir_u8', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'motor_val_u32', 1, 'uint32', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'servo_val_u32', 1, 'uint32', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'blinker_left_u8', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'blinker_right_u8', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    {{'brake_light_u8', 1, 'uint8', -1, 'real', 'Sample', 'Fixed'}} ...
    ] ...
    }})